### ISSUE TITLE
v1.0.0 release

### ISSUE THREAD

**Issue by orlitzky** [brianc/node-buffer-writer#1]
Hello, I'm trying to package buffer-writer for Gentoo Linux. I noticed that package.json has the version at 1.0.0 -- and that's what npm picks up -- but there are no github releases. Would you be willing to make an official release that we could tag as v1.0.0? Otherwise, the next time you commit something, v1.0.0 (obtained from npm) will be different than it is today.

Thanks!

**Comment by brianc** [comment]
what do you mean by github release?  You want me to add a 1.0.0 tag to github?

**Comment by orlitzky** [comment]
On the github project page, where it shows "0 releases", whatever will make that go to "1". I've never done a release on github before =P

Your other projects, for example node-postgres, show "131 releases".

**Comment by brianc** [comment]
Gotcha! Done!

**Comment by orlitzky** [comment]
Awesome, thanks!
